### ISSUE TITLE
یکی از دوره ها رایگان نیست

### ISSUE THREAD

**Issue by sisyx** [barnamenevisi/free-resources#22]
دوره شماره چهار در بخش دوره ها->جاواسکریپت رایگان نیست. یکم هیجان زده شدم که همچین دوره ای پیدا کردم. اما متاسفانه فقط نسخه ی متنیش رایگان هست. تو پرانتز بنویسید (متنی) ایده خوبیه.

**Comment by rzashakeri** [comment]
> دوره شماره چهار در بخش دوره ها->جاواسکریپت رایگان نیست. یکم هیجان زده شدم که همچین دوره ای پیدا کردم. اما متاسفانه فقط نسخه ی متنیش رایگان هست. تو پرانتز بنویسید (متنی) ایده خوبیه.


سلام وقت بخیر 
مرسی که گفتید
برطرف میشه ✅
